package com.daniel.library_management.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Represents a Library Member entity.
 * 
 * <p>Members are registered users who can borrow books from the library.
 * Each member has a unique UUID and membership ID for identification.</p>
 * 
 * <p><strong>Business Rules:</strong></p>
 * <ul>
 *   <li>Email must be unique across all members</li>
 *   <li>Membership ID follows format: LIB-YYYY-XXXXX</li>
 *   <li>Active members can borrow up to 5 books simultaneously</li>
 *   <li>Members with overdue books cannot borrow new books</li>
 * </ul>
 * 
 * @author Daniel
 * @version 1.0.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Member {
    
    /**
     * Unique identifier for the member using UUID format.
     */
    private String id;
    
    /**
     * Member's full name.
     */
    private String name;
    
    /**
     * Member's email address. Must be unique.
     */
    private String email;
    
    /**
     * Unique library membership ID.
     * Format: LIB-YYYY-XXXXX (where XXXXX is sequence number)
     */
    private String membershipId;
    
    /**
     * Member's contact phone number.
     */
    private String phoneNumber;
    
    /**
     * Date when the member joined the library.
     */
    private LocalDate joinDate;
    
    /**
     * Indicates whether the membership is active.
     * Inactive members cannot borrow books.
     */
    @Builder.Default
    private boolean active = true;
    
    /**
     * Creates a new member with auto-generated UUID and membership ID.
     * 
     * @param name Member's full name
     * @param email Member's email address
     * @param phoneNumber Contact phone number
     */
    public Member(String name, String email, String phoneNumber) {
        this.id = UUID.randomUUID().toString();
        this.name = name;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.active = true;
        this.joinDate = LocalDate.now();
        // Membership ID will be generated by the service
    }
}